language: node_js

env:
  global:
    - DISPLAY=':99.0'
  matrix:
    - MOZDOWNLOADPARAMS='-t daily'
    - MOZDOWNLOADPARAMS='-t daily --branch=mozilla-aurora'
    - MOZDOWNLOADPARAMS='-t release -v latest-beta'
    - MOZDOWNLOADPARAMS='-t release -v latest'
    - MOZDOWNLOADPARAMS='-t release -v latest-esr'

before_install:
  - sudo apt-get update -qq

install:
  - sudo apt-get install -y ant python-pip
  - sudo pip install mozdownload==1.12

before_script:
  - sh -e /etc/init.d/xvfb start
  - mozdownload $MOZDOWNLOADPARAMS
  - tar -xf *firefox*.tar.bz2

script:
  - ant test -Dbinary=`pwd`/firefox/firefox

notifications:
  irc:
    channels:
      - "irc.mozilla.org#automation"
      on_success: always
      on_failure: always
      use_notice: true
